server {
    listen 80;
    server_name localhost;

    # Indique à Nginx où se trouvent les fichiers compilés par Vite
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gère correctement les types de fichiers (CSS, JS, etc.)
    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}